frontend/src/component/progress/OptionItem.tsx, frontend/src/component/progress/Progress.tsx, frontend/src/component/progress/ProgressBar.tsx
=> [FE] Hotfix 프로그래스 바 이벤트 추가

.github/workflows/main.yml
- `#13`
- develop-be 브랜치에 pr생성 또는 push 시 테스트 자동 실행 확인
- 테스트용 브랜치입니다....커밋 메세지랑 등등은 무시해주세요..
=> [BE] CICD PR 생성 시 Test 테스트

backend/PR_merge_test.md, backend/src/test/java/com/example/backend/CICDTest.java
- `#13`
- PR TEST report 표시 테스트
- 테스트 중입니다
=> [BE] CI(PR 시 TEST 실행) 테스트

.github/workflows/backend_deploy.yml
- `#13`
- 빌드해서 S3에 업로드하는 깃 액션 .yml 파일 추가
- Git Action 추가는 원하는 브랜치에 바로 안되네요..
=> [BE] PR 후 merge 시 배포 위해 빌드 후 S3 업로드 액션 추가

backend/PR_merge_test.md
- `#13`
- PR 또는 push 시 자동으로 테스트 실행되도록 설정 완료
- test 통과 시 merge 되는지 확인
- CI 테스트중
=> [BE] CI: PR 생성 시 TEST 후 병합 확인

backend/PR_merge_test.md
- PR 제목: `[파트이름] 구현사항 어쩌구 저쩌구` (예: `[FE] Login page UI 구현` )
- PR 작성 후 충돌이 안 나는지 확인, merge후 branch 삭제
- 고민사항은 공유하기
- 위 사항 확인 후 내용 지우기~~
- `#13` 
- pull request merge 시 빌드 후 s3 업로드 확인용 수정
- 테스트하기 빡세네요ㅜ
=> [BE] CD: pull request merge 시 빌드 후 s3 버킷 업로드 확인

backend/PR_merge_test.md
- `#13`
- 전과 같습니다...
- 죄송합니다..
=> [BE] CD S3 업로드 확인용 PR

.github/workflows/backend_test_integration.yml
- `#13`
- Github Actions를 통해 push 또는 pull request 발생 시 gradlew를 사용한 테스트 실행 후 report 보고
- FrontEnd의 경우 테스트 방법 확인 후 적용 예상
- 찐 CI PR입니다...!
- 위의 Action 탭을 이용해 실행된 Action과 결과를 확인할 수 있습니다.
- PR 시 자동으로 테스트 돌리길 원하시면 말씀해주시면 파일 작성해보겠습니다.
=> [BE] Backend CI 구현

frontend/src/component/header/left/ModeSelector.tsx, frontend/src/component/header/right/CarMode.tsx, frontend/src/component/header/right/Dictionary.tsx, frontend/src/component/progress/OptionItem.tsx, frontend/src/component/progress/ProgressBar.tsx
- 폰트 관련해서 수정하고 폰트 사용한 코드 수정했습니다 styled component에서 바로 `${fontname}`의 형식으로 `ex) ${Title1_Medium}` 처럼 사용하시면 됩니다.
=> [FE] 폰트 관련 HOTFIX

.github/workflows/backend_deploy.yml, backend/Dockerfile, backend/Dockerfile_compose, backend/deploy_files/appspec.yml, backend/deploy_files/deploy.sh, docker-compose.yml
- #13 
- Actions를 통해 develop-be 브랜치에 pr 또는 push 시 자동 배포 실행
- Front는 추후에 추가 예정
- 찐 CD PR 입니다.
- FE 배포의 경우 Dockerfile에 내용 수정 및 빌드 과정 수정 후 유사하게 설정하면 될 것 같습니다.
=> [BE] Backend CD 구현

.github/workflows/frontend_deploy.yml, frontend/deploy_files/appspec.yml, frontend/deploy_files/deploy.sh
- #13
- FrontEnd 자동 배포 구현
- GitAction 추가
- 필요한 파일 추가 
- FrontEnd 배포 기능 추가입니다~~~~~
=> [BE] FE CD 기능 추가

.github/workflows/frontend_deploy.yml, frontend/deploy_files/appspec.yml, frontend/deploy_files/deploy.sh
- #13
- build 파일을 압축하여 업로드 하는 과정에서 디렉토리 구조가 수정되는 것을 확인하여 이에 맞게 수정하였습니다.
- 수정사항ㅎㅎ...또 log 더럽히고 싶지 않아요ㅜ
=> [BE] FE CD 기능 오류 수정

frontend/src/App.tsx, frontend/src/assets/icons/more1.svg, frontend/src/assets/icons/more2.svg, frontend/src/component/common/icons.tsx, frontend/src/component/main/MainContainer.tsx, frontend/src/component/main/trimCard/TrimCard.tsx, frontend/src/pages/Main.tsx, frontend/src/style/theme.tsx
- #60
- 메인페이지 UI 구현했습니다 대부분의 모니터에서 UI가 이상하게 배치되지 않도록 신경썼어요
=> [FE] 메인 페이지 UI 작성

frontend/src/component/content/right/Footer.tsx, frontend/src/component/content/right/OptionCardList.tsx, frontend/src/component/content/right/OptionInfo.tsx, frontend/src/component/content/right/card/DetailToggle.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/component/content/right/optioninfo/Estimate.tsx, frontend/src/component/content/right/optioninfo/Modal.tsx, frontend/src/component/content/right/optioninfo/estimate/Selection.tsx
- #49
- 하단 모달 UI 구현
- 사각형으로 표시한 영역이 데이터가 보여지고 스크롤 되는 영역입니다.
- 하단모달 애니메이션 구현
- 하단모달 창이 보이지 않는 순간에 총 견적보기 버튼을 클릭하면 하단모달 창이 아래에서 위로 올라옵니다.
- 모달창이 보이는 순간에 모달창의 `X`아이콘 혹은, 총 견적보기 버튼을 클릭하면 하단모달 창이 위에서 아래로 내려갑니다.
- 제가 구현한 부분에도 오늘 수정한 폰트를 적용했습니다.
- 모달 내부에서 재사용 가능한 요소들을 Styled Component로 만들어보려고 노력했습니다.
- 모달 내부에 보여지는 선택한 옵션에 대한 정보를 보여주는 커다란 `Box`
- `Box`내부는 다시 `Header`와 `Selection`의 리스트로 이루어져 있습니다.
```js
// Box 컴포넌트
function Estimate() {
return (
<Wrapper>
<Header>
<OptionText>팰리세이드 Le Blanc (르블랑)</OptionText>
<Price>+ 43,460,000원</Price>
</Header>
<SelectionList>
<Selection></Selection>
<Selection></Selection>
<Selection></Selection>
</SelectionList>
</Wrapper>
);
}
```
```js
function Selection() {
return (
<Wrapper>
<Option>
<OptionTitle>파워트레인</OptionTitle>
<OptionName>디젤 2.2</OptionName> …
```
=> [FE] 하단모달 UI, 애니메이션 구현

frontend/src/component/content/right/OptionCardList.tsx, frontend/src/component/content/right/card/DetailToggle.tsx, frontend/src/component/content/right/card/OptionCard.tsx
- #68 ( #이슈번호 )
- 옵션카드 컴포넌트 `map`으로 생성
- 옵션카드 클릭시 클릭한 옵션카드 css변경, 애니메이션 구현
=> [FE] 옵션카드 선택 애니미에션 구현

backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java, backend/src/main/java/com/example/backend/domain/information/controller/IntroController.java, backend/src/main/java/com/example/backend/domain/information/dto/IntroResponse.java, backend/src/main/java/com/example/backend/domain/information/dto/SimpleColorResponse.java, backend/src/main/java/com/example/backend/domain/information/mapper/IntroSourceMapper.java, backend/src/main/java/com/example/backend/domain/information/model/car/entity/ExteriorColor.java, backend/src/main/java/com/example/backend/domain/information/model/car/entity/InteriorColor.java, backend/src/main/java/com/example/backend/domain/information/model/car/entity/TrimInterior.java, backend/src/main/java/com/example/backend/domain/information/model/car/repository/TrimInteriorRepository.java, backend/src/main/java/com/example/backend/domain/information/model/car/repository/TrimInteriorRowMapper.java, backend/src/main/java/com/example/backend/domain/information/service/ColorService.java, backend/src/main/resources/sql/data.sql, backend/src/main/resources/sql/scheme.sql
- #85 
- 외장색상과 거의 동일하게 구현
- 내장색상 트림 별로 조회되도록 구현
- data.sql에 아이디 순차 증가 되도록 통일시킴
- ASAP
=> [BE] 메인화면에 들어갈 트림 별 내장색상 조회 API

frontend/src/App.tsx, frontend/src/component/content/Content.tsx, frontend/src/component/content/left/OptionImage.tsx, frontend/src/component/content/right/Footer.tsx, frontend/src/component/content/right/OptionCardList.tsx, frontend/src/component/content/right/OptionInfo.tsx, frontend/src/component/content/right/card/FeedBack.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/component/loding/Bottom.tsx, frontend/src/component/loding/LoadingAnimation.tsx, frontend/src/component/loding/ProgressIndicator.tsx, frontend/src/pages/Loading.tsx
- #106 ( #이슈번호 )
- 피드백 컴포넌트 UI구현
- 아이콘 애니메이션 구현
- 선택완료 클릭시 다음 옵션으로 넘어가기 구현
=> [FE] 선택 피드백 제공기능 구현

iOS_H3/iOS_H3.xcodeproj/project.pbxproj, iOS_H3/iOS_H3/Source/CarMakingMode.swift, iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift, iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift, iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift, iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift, iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonViewController.swift, iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift, iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift, iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift, iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift, iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
- #128 
- `CarMakingMode` 구현했습니다 (selfMode와 guideMode)
- `OptionCardButton`의 `OptionCardType` 삭제 후 `CarMakingMode`로 수정했습니다
화이팅입니다!
=> [iOS] CarMakingMode 구현

frontend/.env, frontend/src/api/fetchData.ts, frontend/src/component/hooks/useFetch.ts, frontend/src/component/hooks/useScroll.ts, frontend/src/component/main/MainContainer.tsx, frontend/src/component/main/modelOption/default/ModelDefaultOption.tsx, frontend/src/component/main/modelOption/default/ModelOptionDetail.tsx, frontend/src/component/main/modelOption/inner/ModelInnerOption.tsx, frontend/src/component/main/modelOption/inner/ModelOptionDetail.tsx, frontend/src/component/main/modelOption/outer/ModelOptionDetail.tsx, frontend/src/component/main/modelOption/outer/ModelOuterOption.tsx, frontend/src/component/util/sortData.ts
- api관련 이슈 적을 예정
- 먼저 fetch하는 hook을 만들어놨어요
```
import { useState, useEffect } from 'react';
interface FetchResult<T> {
data: T | null;
error: Error | null;
loading: boolean;
}
interface ApiResponse<T> {
data: T;
}
function useFetch<T>(url: string): FetchResult<T> {
const [data, setData] = useState<T | null>(null);
const [error, setError] = useState<Error | null>(null);
const [loading, setLoading] = useState(true);
useEffect(() => {
async function fetchData() {
try {
const response = await fetch(import.meta.env.VITE_API_URL + url);
if (!response.ok) {
throw new Error(`Failed to fetch: ${response.statusText}`);
}
const result: ApiResponse<T> = await response.json();
setData(result.data);
} catch (error) {
setError(error as Error);
} finally {
setLoading(false);
}
}
fetchData();
}, [url]); …
```
=> [FE] 메인 페이지 API 연결

iOS_H3/iOS_H3.xcodeproj/project.pbxproj, iOS_H3/iOS_H3/Source/App/SceneDelegate.swift, iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift, iOS_H3/iOS_H3_UI/BottomModalView.swift, iOS_H3/iOS_H3_UI/BottomModalViewController.swift, iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift, iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift, iOS_H3/iOS_H3_UI/CarMakingContentView/PageSection.swift, iOS_H3/iOS_H3_UI/CarMakingProgressBar/CarMakingProgressBar.swift, iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift, iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBar.swift, iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBarViewController.swift
- #131 
- `@objc` 프로토콜로 수정했습니다.
- `@objc optional` 사용하여 선택적으로 delegate 메소드들을 구현할 수 있도록 수정했습니다.
- 이유 : OhMyCarSetTitleBar에는 NavigationBarType이 4가지가 존재하는데 메인, 셀프모드, 가이드모드에서는 온보딩에서만 skipButton이 사용되지 않고 반대의 경우도 마찬가지입니다. 그래서 모든 타입에 공통적으로 존재하는 요소인 BackButton 클릭 관련 메소드를 제외한 delegate 메소드는 옵셔널로 처리해주었습니다.
- 수업시간에 배운 Delegate 메소드명 규칙에 따라 메소드명을 수정했습니다.
- CarMakingContentViewDataSource 메소드 중 사용되지 않는 `numberOfSections()`, `contentView(numberOfItemsInSection:)`, `contentView(stepAtIndexPath:)` 메소드를 삭제했습니다
- 마찬가지로 DataSource 메소드명 규칙에 따라 메소드명을 수정했습니다.
- init시 `CarMakingMode` (셀프모드 혹은 가이드모드) 를 전달하여 인스턴스를 생성합니다. 
=> `CarMakingViewController(mode: .selfMode)`
**스크린샷**
`CarMakingContentViewDataSource` 메소드명 수정 시 규칙에 따라 첫번째 매개변수에 자기 자신의 인스턴스를 넣으려고 했는데
`Reference to generic type 'CarMakingContentView' requires …
=> [iOS] 내차만들기 ViewController 구현

backend/src/main/java/com/example/backend/domain/intro/controller/IntroController.java, backend/src/main/java/com/example/backend/domain/intro/dto/EstimateResponse.java, backend/src/main/java/com/example/backend/domain/intro/service/InitialService.java
- #120 
- 그냥 하드코딩
- 같은 파트원에게 하고싶은 말
=> [BE] 초기 견적값 반환 API

frontend/.env, frontend/src/component/header/left/Logo.tsx, frontend/src/component/header/left/ModeSelector.tsx, frontend/src/component/header/right/CarMode.tsx, frontend/src/component/main/MainContainer.tsx, frontend/src/component/modal/ModalLayout.tsx, frontend/src/component/modal/exit/ExitModal.tsx, frontend/src/component/modal/modeChange/GuideChangeModal.tsx
- #15
- 팝업 이벤트(메인로고, 모드 변경, 모델 변경) 연동했습니다.
=> [FE] 팝업 이벤트 연동 구현

frontend/src/component/content/Content.tsx, frontend/src/pages/Self.tsx
=> fix: 레이아웃 버그 수정(#141)

frontend/src/App.tsx, frontend/src/component/content/Content.tsx, frontend/src/component/content/contentInterface.tsx, frontend/src/component/content/left/OptionImage.tsx, frontend/src/component/content/right/OptionInfo.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/component/main/modelOption/default/ModelDefaultOption.tsx, frontend/src/component/util/getCategory.ts, frontend/src/pages/Self.tsx, frontend/src/provider/selectedOptionProvider.tsx
=> [FE] 옵션 데이터 api 연결

frontend/src/component/common/DetilBox.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/component/content/totalestimate/estimatecontent/Bottom.tsx, frontend/src/component/content/totalestimate/estimatecontent/EstimateHeader.tsx, frontend/src/component/content/totalestimate/estimatecontent/bottom/DetailEstimate.tsx
- #152
- 자세히보기 컴포넌트 Parameter 설정해서 재사용
useFetch가 이전 데이터 길이를 기준으로 API를 호출하네욥
=> [FE] DetailBox 공통 컴포넌트로 분리

backend/src/main/java/com/example/backend/domain/global/model/enums/ResultCode.java, backend/src/main/java/com/example/backend/domain/global/utils/StringUtils.java, backend/src/main/java/com/example/backend/domain/information/model/car/repository/ExteriorColorRepository.java, backend/src/main/java/com/example/backend/domain/information/service/strategy/ExteriorColorService.java, backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java, backend/src/main/java/com/example/backend/domain/sale/dto/SalesSummaryResponse.java, backend/src/main/java/com/example/backend/domain/sale/entity/OptionSalesSummary.java, backend/src/main/java/com/example/backend/domain/sale/entity/SaleSummary.java, backend/src/main/java/com/example/backend/domain/sale/entity/SalesOptions.java, backend/src/main/java/com/example/backend/domain/sale/entity/SalesSummary.java, backend/src/main/java/com/example/backend/domain/sale/mapper/SelectionRatioRowMapper.java, backend/src/main/java/com/example/backend/domain/sale/mapper/SummaryMapper.java, backend/src/main/java/com/example/backend/domain/sale/repository/SalesOptionsRepository.java, backend/src/main/java/com/example/backend/domain/sale/repository/SalesRepository.java, backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java, backend/src/main/java/com/example/backend/domain/sale/service/OptionSaleRatioServiceImpl.java, backend/src/main/java/com/example/backend/domain/sale/service/RatioService.java, backend/src/main/java/com/example/backend/domain/sale/service/SaleRatioServiceImpl.java, backend/src/main/java/com/example/backend/domain/sale/service/SelfModeService.java, backend/src/main/java/com/example/backend/domain/sale/service/SelfModeServiceFactory.java, backend/src/test/java/com/example/backend/domain/information/service/strategy/ExteriorColorServiceTest.java
- #121 
외장색, 내장색, 휠, 추가옵션 구현
파워트레인, 바디타입, 드라이브 시스템은 수정 필요
- 머지하고 브랜치 지우지 마세여 빠른 배포를 위해 계속 PR 날릴게요
=> [BE] (셀프모드) 옵션 선택률 API 일부 구현

backend/src/main/java/com/example/backend/domain/global/utils/StringUtils.java, backend/src/main/java/com/example/backend/domain/information/model/car/entity/ExteriorColor.java, backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java, backend/src/main/java/com/example/backend/domain/sale/repository/SalesRepository.java, backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java, backend/src/main/java/com/example/backend/domain/sale/service/SelfModeServiceFactory.java, backend/src/main/java/com/example/backend/domain/sale/service/VehicleSpecificationSaleRatioServiceImpl.java, backend/src/main/java/com/example/backend/domain/sale/service/VehicleTypeSaleRatioServiceImpl.java
=> [BE] (셀프모드) 옵션 선택률 API 완성

frontend/src/App.tsx, frontend/src/component/common/DetilBox.tsx, frontend/src/component/content/Content.tsx, frontend/src/component/content/right/Footer.tsx, frontend/src/component/content/right/OptionCardList.tsx, frontend/src/component/content/right/OptionInfo.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/provider/selectedOptionProvider.tsx, frontend/src/provider/tempOptionProvider.tsx
- Context 사용으로 중복 props 제거했습니다.
=> [FE] Context 사용으로 중복되는 props 제거

backend/src/main/java/com/example/backend/domain/guide/controller/TagController.java, backend/src/main/java/com/example/backend/domain/guide/dto/TagInformationResponse.java, backend/src/main/java/com/example/backend/domain/guide/dto/TagListResponse.java, backend/src/main/java/com/example/backend/domain/guide/entity/Tag.java, backend/src/main/java/com/example/backend/domain/guide/mapper/TagInformationMapper.java, backend/src/main/java/com/example/backend/domain/guide/repository/TagRepository.java, backend/src/main/java/com/example/backend/domain/guide/service/TagService.java, backend/src/main/java/com/example/backend/domain/sale/entity/Sales.java
=> [BE] 태그 목록 반환하는 API

backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java
- #121
- 한 것들 적기
- 같은 파트원에게 하고싶은 말
=> [BE]선택률 Request Uri 수정 

backend/src/main/java/com/example/backend/domain/cardb/service/CardbService.java, backend/src/main/java/com/example/backend/domain/global/model/enums/ResultCode.java, backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java, backend/src/main/java/com/example/backend/domain/information/dto/CommentResponse.java, backend/src/main/java/com/example/backend/domain/information/model/car/repository/ExteriorColorRepository.java, backend/src/main/java/com/example/backend/domain/information/model/car/repository/InteriorColorRepository.java, backend/src/main/java/com/example/backend/domain/information/model/option/repository/BodytypeRepository.java, backend/src/main/java/com/example/backend/domain/information/model/option/repository/DrivingSystemRepository.java, backend/src/main/java/com/example/backend/domain/information/model/option/repository/PowertrainRepository.java, backend/src/main/java/com/example/backend/domain/information/model/option/repository/WheelRepository.java, backend/src/main/java/com/example/backend/domain/information/service/AdditionalOptionService.java, backend/src/main/java/com/example/backend/domain/information/service/DetailService.java, backend/src/main/java/com/example/backend/domain/information/service/InformationStrategyFactory.java, backend/src/main/java/com/example/backend/domain/information/service/InteriorColorService.java, backend/src/main/java/com/example/backend/domain/information/service/strategy/BodytypeService.java, backend/src/main/java/com/example/backend/domain/information/service/strategy/DrivingSystemService.java, backend/src/main/java/com/example/backend/domain/information/service/strategy/ExteriorColorService.java, backend/src/main/java/com/example/backend/domain/information/service/strategy/InformationStrategy.java, backend/src/main/java/com/example/backend/domain/information/service/strategy/PowertrainService.java, backend/src/main/java/com/example/backend/domain/information/service/strategy/WheelService.java, backend/src/test/java/com/example/backend/domain/information/controller/ColorInformationControllerTest.java, backend/src/test/java/com/example/backend/domain/information/service/strategy/InteriorColorServiceTest.java
- #173, #123
- starategyFactory 사용해 id로 단일 조회하는 기능 구현 
- 견적보기에서 사용 예정
=> [BE] 자동차 부품 아이디로 단일 조회 하는 API

frontend/src/component/common/DetilBox.tsx, frontend/src/component/content/Content.tsx, frontend/src/component/content/right/card/DetailToggle.tsx, frontend/src/component/content/right/card/OptionCard.tsx
- #146 
- 자세히 보기 toggle hover시에 데이터 요청 & 데이터 요청 하기 전 cache된 데이터가 있으면 그대로 가져다 쓰도록 구현했습니다.
=> [FE] 자세히 보기 내용 cache화 및 최적화

backend/src/main/java/com/example/backend/domain/guide/dto/EstimateRequest.java, backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java, backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java, backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersService.java, backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersServiceImpl.java
- #122 , #123 
- 충돌 난 거 해결했어여
- 배포하느라 고생이 많으십니다
=> [BE] guide_mode와 유사 사용자 구매율 API merge conflict 해결

frontend/src/App.tsx, frontend/src/component/common/DetailSelectedBox.tsx, frontend/src/component/content/SelectedOptionContent.tsx, frontend/src/component/content/left/AdditionalOptionImage.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/provider/tempImageProvider.tsx
- #230 
- 선택옵션에서 세부사항도 이미지 보이도록 처리했습니다.
- 하고싶어서 애니메이션 삽질을 좀 오래해서 ... 좀 더 하면 될 것 같은데 일단 기능구현이 먼저라 보이게만 해두었습니다.
https://github.com/softeerbootcamp-2nd/H3-UmochaRacer/assets/15906101/b9793471-37a7-4028-b6b4-7e4856bff768
=> [FE] 선택 옵션 이미지 세부사항 보이기 구현

.github/workflows/frontend_deploy.yml, frontend/src/component/common/EstimateList.tsx, frontend/src/component/common/Warning.tsx, frontend/src/component/content/Content.tsx, frontend/src/component/content/right/Footer.tsx, frontend/src/component/content/right/OptionCardList.tsx, frontend/src/provider/optionProvider.tsx, frontend/src/provider/selectedOptionProvider.tsx, frontend/src/provider/tempOptionProvider.tsx
=> [FE] 자잘한 수정 및 배포 수정

frontend/src/component/content/Content.tsx, frontend/src/component/content/contentInterface.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/component/content/right/card/Tag.tsx
- #234 
- 가이드 모드 옵션카드 스타일 변경
- 가이드 모드 태그 컴포넌트 구현
=> [FE] 옵션카드 모드 별 스타일 변경 

frontend/src/component/content/Content.tsx, frontend/src/component/content/right/SelectedOptionInfo.tsx, frontend/src/component/content/right/card/OptionCard.tsx, frontend/src/component/guidecontent/guideestimate/EstimateContent.tsx, frontend/src/provider/modalProvider.tsx
=> [FE] 자잘한 QA 및 불필요한 렌더링 수정

backend/src/main/java/com/example/backend/domain/sale/mapper/SummaryMapper.java, backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java, backend/src/main/java/com/example/backend/domain/sale/repository/TagRatioTemplateRepository.java, backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersServiceImpl.java
조회된 결과 없음 -> mapper에서  size-1 로 접근할 때 IndexOutOfBoundException 예외 발생
-IndexOutOfBoundException 예외처리 
- 같은 파트원에게 하고싶은 말
=> [BE] (가이드모드) 나와 비슷한 사용자 선택률 API에 해당하는 데이터 없을 때 예외처리
